name: Merge Release Branch
 
on:
  push:
    branches:
      - 'release'
 
jobs:
  merge-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
 
      - name: Merge Release to Develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff release || exit 1
          git push origin develop
 
  merge-to-master:
    runs-on: ubuntu-latest
    needs: merge-to-develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
 
      - name: Merge Release to Master
        run: |
          git checkout master
          git pull origin master
          git merge --no-ff -X theirs release
          git push origin master
 
      - name: Create Release Tag
        run: |
          git tag -a v$(date +'%Y%m%d%H%M%S') -m "Release"
          git push origin --tags
 
      - name: Delete Release Branch
        run: |
          git push origin --delete release
 
